### ISSUE TITLE
Lambda event not always included in error

### ISSUE THREAD

**Issue by teebu** [arabold/serverless-sentry-lib#4]
When lambda returns an error, the `event` is missing in the report sometimes. I'm guessing it's because it's an unhandled error?

I'd like to always return the `event` will every error. 

The `extra: { },` is empty in the json.

**Comment by arabold** [comment]
Hi @teebu and thanks for your bug report. I'm not sure if I can follow what exactly is going wrong though. Even in case of an unhandled exception it _should_ log the exception to Sentry with all details as usual, including the event data, and then abort the wrapped Lambda function handler with an empty response. From what I see in our own logs this works pretty reliable. Could Sentry automatically filter the event for sensitive information such as passwords or authentication tokens in your case? Otherwise, do you have a sample code where this happens?

**Comment by teebu** [comment]
I've narrowed down to where the problem is happening, but I don't know why. The scrubber is not the issue, I disabled that. 

Here's a sample lambda:

https://gist.github.com/teebu/0a230908ae5ac0824e115ac8a6dae237

For some reason the download module is interfering with raven.

**Comment by arabold** [comment]
Closing as outdated. v2.0.0 has been released. If this is still a problem please create a new issue.
